# Generated by Django 3.1.4 on 2020-12-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ID', models.CharField(max_length=200, null=True)),
                ('Password', models.CharField(max_length=200, null=True)),
                ('Ph_no', models.IntegerField(max_length=200, null=True)),
                ('E_Mail', models.CharField(max_length=200, null=True)),
                ('Role', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='Dish_ID',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=200, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Order_Type', models.CharField(choices=[('Take-away', 'Take-away'), ('Delivery', 'Delivery')], max_length=200, null=True)),
                ('Payment_Status', models.CharField(choices=[('Pending', 'Pending'), ('Recieved', 'Recieved')], max_length=200, null=True)),
                ('Destination', models.CharField(max_length=200, null=True)),
                ('Tax', models.FloatField(max_length=200, null=True)),
                ('Overdue', models.FloatField(max_length=200, null=True)),
                ('Total_Amount', models.FloatField(max_length=200, null=True)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(max_length=200, null=True)),
                ('Dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dish')),
                ('Order_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(max_length=200, null=True)),
                ('Dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dish')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profile')),
            ],
        ),
    ]
