# Generated by Django 3.1.4 on 2020-12-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201214_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='Offer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Ph_no',
            field=models.IntegerField(null=True),
        ),
    ]
