# Generated by Django 3.1.4 on 2020-12-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20201214_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='Dish_ID',
        ),
    ]
