# Generated by Django 3.1.4 on 2020-12-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20201222_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Order_ID',
        ),
        migrations.AlterField(
            model_name='order',
            name='Overdue',
            field=models.FloatField(default=0.0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Tax',
            field=models.FloatField(default=0.0, max_length=200, null=True),
        ),
    ]
