# Generated by Django 3.1.4 on 2020-12-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20201222_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='Dish_File_Path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dish',
            name='Dish_Type',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Chinesse', 'Chinesse'), ('Western', 'Western'), ('Beverages', 'Beverages')], max_length=200, null=True),
        ),
    ]
